FROM node:20-slim

LABEL org.opencontainers.image.authors="Elias Shekh"

# Install OpenSSL and postgresql-client for Prisma
RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json .

RUN npm i -g pnpm

RUN pnpm i

COPY . .

CMD ["sh", "-c", "sleep 10 && pnpm run db:generate && pnpm run db:push && pnpm run jest"]
