services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres_pgadmin
    env_file:
      - .env
    ports:
      - '4000:80'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  node_server:
    build:
      context: .
      dockerfile: Dockerfile.Dev
    container_name: node_server_container
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
  pgadmin_data:
