FROM node:22-alpine

LABEL org.opencontainers.image.authors="Elias Shekh"

WORKDIR /app

COPY package.json .

RUN npm i -g pnpm && pnpm i

COPY . .

CMD ["sh", "-c", "pnpm db:generate && pnpm db:push && pnpm nest:dev"]

EXPOSE 8000
