services:
  postgres_test:
    image: postgres:17
    container_name: postgres_test_container
    env_file:
      - .env.test
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  node_server_test:
    build:
      context: .
      dockerfile: Dockerfile.Test
    container_name: node_server_test_container
    depends_on:
      postgres_test:
        condition: service_healthy
    env_file:
      - .env.test
    ports:
      - '8000:8000'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'node -e "fetch(''http://localhost:8000/'').then(res => (res.ok ? process.exit(0) : process.exit(1))).catch(() => process.exit(1));"'
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - node_server_test_data:/app
      - /app/node_modules

volumes:
  node_server_test_data:
  postgres_test_data:
