services:
  postgres_test:
    image: postgres:17
    container_name: postgres_test_container
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
